### PR TITLE
Add version & pre-publish scripts

### PR DESCRIPTION
**Pull request by jhermsmeier**

### CODE REVIEW

**Comment by jhermsmeier** [comment]
It appears there's something wrong with the cache on AppVeyor

**Comment by lurch** [comment]
I tried logging in to AppVeyor to restart the build for you, but it seems that `resin-io/etcher` is the only repo on which I have build-restart permissions.

**Comment by jhermsmeier** [comment]
Thanks, I've already restarted it, but it keeps blowing up – and then I left that comment to remind me to debug this today.

**Comment by jhermsmeier** [comment]
I works again now; possibly either an npm issue, or because AppVeyor switched latest node from v7.6.x to v7.7.x.

**Comment by lurch** [comment]
Would it be possible to bring this more in line with the "resin.io standard" way of using `versionist` ?
(or are there good reasons for doing it differently?)

**Comment by jhermsmeier** [comment]
Closing, as this is stale and superseded by versionbot etc.

**Pull request closed without merging**
