### PR TITLE
Transform._flush is public

### PR DESCRIPTION
**Pull request by zvin**

### CODE REVIEW

**Comment by lurch** [comment]
I dunno what the conventions are in the Nodejs-world, but in the Python-world a leading-underscore typically indicates an 'internal' method (so seeing a public method with a leading underscore looks a bit weird).
I wonder if it's worth creating a "public flush" method which simply calls the "protected _flush" method? :man_shrugging: :man_shrugging:

**Comment by jhermsmeier** [comment]
@lurch they are pretty much the same indeed – [`transform._flush()`](https://nodejs.org/api/stream.html#stream_transform_flush_callback) is called by the stream's internals before ending the stream. There's no corresponding public `.flush()`, as that could mess things up, given it's designed to be called in the end. You can still run it "manually" by `.end()`-ing the stream though.

**Comment by zvin** [comment]
This PR is for matching @types/node `Transform` where it is public https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/stream.d.ts#L281

**Comment by lurch** [comment]
Sorry, I didn't realise that this was about aligning with some external API, I'll crawl back under my rock! :wink:

**Review by thundron — APPROVED** [review]

**Pull request merged**
