### PR TITLE
Improve usage examples in README

### PR DESCRIPTION
**Pull request by jhermsmeier**
Connects to #10

### CODE REVIEW

**Comment by jviotti** [comment]
Looks good, and I'll approve, however I wonder if we should be auto-generating this from JSDoc annotations instead.

**Review by jviotti — APPROVED** [review]

**Comment by jhermsmeier** [comment]
> however I wonder if we should be auto-generating this from JSDoc annotations instead.

That would of course be preferable, but would make it more complicated to show off things like verification (as it's not a method, and thus doesn't have docs associated), and also splitting the quite noisy API docs from these examples. Or is there a beautifully easy way of doing this?

**Comment by jviotti** [comment]
I believe you can include module-scope examples, while also provide some docs for the methods/properties, but definitely not high priority for now. We can experiment with it after v1.

**Comment by jhermsmeier** [comment]
Aye, sounds good.

**Pull request merged**
